name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Prepare build artifacts
        run: |
          mkdir -p build
          cp dist/coupons-widget.min.js build/d.min.js

      - name: Add version info
        run: |
          VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[:space:]')
          BUILD_TIME=$(date '+%Y-%m-%d %H:%M:%S')
          echo "/*! v${VERSION}" > build/d.min.js.tmp
          echo " * Build time: ${BUILD_TIME}" >> build/d.min.js.tmp
          echo " */" >> build/d.min.js.tmp
          cat build/d.min.js >> build/d.min.js.tmp
          mv build/d.min.js.tmp build/d.min.js

      - name: Upload to S3
        env:
          ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          REGION: ${{ secrets.S3_REGION }}
          BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME || 'scripts' }}
          FILE_KEY: ${{ secrets.S3_FILE_KEY || 'coupons-widget.min.js' }}
        run: node ./scripts/send.js
